apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssspro-test-redis-pvc
  labels:
    username: ssspro
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi