apiVersion: v1
kind: Service
metadata:
  name: ssspro-test-redis
  labels:
    username: ssspro
    env: test
spec:
  type: ClusterIP
  selector:
    app: ssspro-test-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379